name: OwnVoiceSystem
main: de.teddy.Handler
version: 0.1
label: OwnVoiceSystem

intents:
  - GUILD_VOICE_STATES
  - GUILDS

description:
  Ein System, mit dem eigene Sprachkanäle erstellen werden können.